service: todoapp

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2
  deploymentPrefix: todoapp
  deploymentBucket:
    name: ${file(./env/variables.js):bucketName}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todo
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          method: GET
          path: /hello

plugins:
  - serverless-esbuild
  - serverless-offline
